




const GET_NOTEBOOKS = 'notebooks/GET_NOTEBOOKS';
const NOTEBOOK_FOR_PAGE = 'notebooks/NOTEBOOK_FOR_PAGE';
const CREATE_NEW_NOTEBOOK = 'notebooks/CREATE_NEW_NOTEBOOK';
const DELETE_NOTEBOOK = 'notebooks/DELETE_NOTEBOOK';
const UPDATE_NOTEBOOK = 'notebooks/UPDATE_NOTEBOOK';
const GET_LIMIT_NOTEBOOKS = 'notebooks/GET_LIMIT_NOTEBOOKS';

export {
  GET_NOTEBOOKS,
  NOTEBOOK_FOR_PAGE,
  CREATE_NEW_NOTEBOOK,
  DELETE_NOTEBOOK,
  UPDATE_NOTEBOOK,
  GET_LIMIT_NOTEBOOKS,



};
